// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.20.3
// source: article.proto

package article

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ArticleService_GetSubscribedArticle_FullMethodName = "/article.ArticleService/GetSubscribedArticle"
	ArticleService_UserFollowArticle_FullMethodName    = "/article.ArticleService/UserFollowArticle"
	ArticleService_UserUnFollowArticle_FullMethodName  = "/article.ArticleService/UserUnFollowArticle"
)

// ArticleServiceClient is the client API for ArticleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ArticleServiceClient interface {
	GetSubscribedArticle(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetSubscribedArticleResponse, error)
	UserFollowArticle(ctx context.Context, in *UserFollowArticleRequest, opts ...grpc.CallOption) (*UserFollowArticleResponse, error)
	UserUnFollowArticle(ctx context.Context, in *UserUnFollowArticleRequest, opts ...grpc.CallOption) (*UserUnFollowArticleResponse, error)
}

type articleServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewArticleServiceClient(cc grpc.ClientConnInterface) ArticleServiceClient {
	return &articleServiceClient{cc}
}

func (c *articleServiceClient) GetSubscribedArticle(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetSubscribedArticleResponse, error) {
	out := new(GetSubscribedArticleResponse)
	err := c.cc.Invoke(ctx, ArticleService_GetSubscribedArticle_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *articleServiceClient) UserFollowArticle(ctx context.Context, in *UserFollowArticleRequest, opts ...grpc.CallOption) (*UserFollowArticleResponse, error) {
	out := new(UserFollowArticleResponse)
	err := c.cc.Invoke(ctx, ArticleService_UserFollowArticle_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *articleServiceClient) UserUnFollowArticle(ctx context.Context, in *UserUnFollowArticleRequest, opts ...grpc.CallOption) (*UserUnFollowArticleResponse, error) {
	out := new(UserUnFollowArticleResponse)
	err := c.cc.Invoke(ctx, ArticleService_UserUnFollowArticle_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ArticleServiceServer is the server API for ArticleService service.
// All implementations must embed UnimplementedArticleServiceServer
// for forward compatibility
type ArticleServiceServer interface {
	GetSubscribedArticle(context.Context, *Empty) (*GetSubscribedArticleResponse, error)
	UserFollowArticle(context.Context, *UserFollowArticleRequest) (*UserFollowArticleResponse, error)
	UserUnFollowArticle(context.Context, *UserUnFollowArticleRequest) (*UserUnFollowArticleResponse, error)
	mustEmbedUnimplementedArticleServiceServer()
}

// UnimplementedArticleServiceServer must be embedded to have forward compatible implementations.
type UnimplementedArticleServiceServer struct {
}

func (UnimplementedArticleServiceServer) GetSubscribedArticle(context.Context, *Empty) (*GetSubscribedArticleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSubscribedArticle not implemented")
}
func (UnimplementedArticleServiceServer) UserFollowArticle(context.Context, *UserFollowArticleRequest) (*UserFollowArticleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserFollowArticle not implemented")
}
func (UnimplementedArticleServiceServer) UserUnFollowArticle(context.Context, *UserUnFollowArticleRequest) (*UserUnFollowArticleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserUnFollowArticle not implemented")
}
func (UnimplementedArticleServiceServer) mustEmbedUnimplementedArticleServiceServer() {}

// UnsafeArticleServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ArticleServiceServer will
// result in compilation errors.
type UnsafeArticleServiceServer interface {
	mustEmbedUnimplementedArticleServiceServer()
}

func RegisterArticleServiceServer(s grpc.ServiceRegistrar, srv ArticleServiceServer) {
	s.RegisterService(&ArticleService_ServiceDesc, srv)
}

func _ArticleService_GetSubscribedArticle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleServiceServer).GetSubscribedArticle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArticleService_GetSubscribedArticle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleServiceServer).GetSubscribedArticle(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArticleService_UserFollowArticle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserFollowArticleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleServiceServer).UserFollowArticle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArticleService_UserFollowArticle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleServiceServer).UserFollowArticle(ctx, req.(*UserFollowArticleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArticleService_UserUnFollowArticle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserUnFollowArticleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleServiceServer).UserUnFollowArticle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArticleService_UserUnFollowArticle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleServiceServer).UserUnFollowArticle(ctx, req.(*UserUnFollowArticleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ArticleService_ServiceDesc is the grpc.ServiceDesc for ArticleService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ArticleService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "article.ArticleService",
	HandlerType: (*ArticleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSubscribedArticle",
			Handler:    _ArticleService_GetSubscribedArticle_Handler,
		},
		{
			MethodName: "UserFollowArticle",
			Handler:    _ArticleService_UserFollowArticle_Handler,
		},
		{
			MethodName: "UserUnFollowArticle",
			Handler:    _ArticleService_UserUnFollowArticle_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "article.proto",
}
