// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"article_demo/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/article/get",
				Handler: GetSubscribedArticleHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/article/follow",
				Handler: UserFollowArticleHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/article/unFollow",
				Handler: UserUnFollowArticleHandler(serverCtx),
			},
		},
	)
}
