// Code generated by goctl. DO NOT EDIT.
package types

type GetUserByIdRequest struct {
	Id int64 `form:"id"`
}

type Response struct {
	Code int         `json:"code"`
	Msg  string      `json:"msg"`
	Data interface{} `json:"data"`
}
